name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

permissions:
  contents: write

jobs:
  Release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"

      - name: Set up MsBuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Read version tag
        id: read_version
        run: node.exe .github/workflows/version.js

      - name: Generate project files
        shell: cmd
        run: premake5 vs2022

      - name: Core - Build
        shell: cmd
        run: |
          @echo off
          msbuild "build/III.VC.CLEO.sln" /property:Configuration=Release /property:Platform=Win32 /m /fileLogger1 /fileLoggerParameters1:warningsOnly;errorsOnly;logfile=output.log
          node .github/workflows/analyze-build-log.js "Core compilation"

      - name: Core - VirusTotal scan III
        id: scan_III
        env:
          vt_key: ${{secrets.VT_KEY}}
        if: ${{env.vt_key != ''}}
        uses: crazy-max/ghaction-virustotal@d34968c958ae283fe976efed637081b9f9dcf74f # v4.2.0
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          files: './bin/III.CLEO.asi'

      - name: Core - VirusTotal log III
        if: steps.scan_III.outcome == 'success'
        run: echo "::notice title=III.CLEO Core virus scan::${{steps.scan_III.outputs.analysis}}"

      - name: Core - VirusTotal scan VC
        id: scan_VC
        env:
          vt_key: ${{secrets.VT_KEY}}
        if: ${{env.vt_key != ''}}
        uses: crazy-max/ghaction-virustotal@d34968c958ae283fe976efed637081b9f9dcf74f # v4.2.0
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          files: './bin/VC.CLEO.asi'

      - name: Core - VirusTotal log VC
        if: steps.scan_VC.outcome == 'success'
        run: echo "::notice title=VC.CLEO Core virus scan::${{steps.scan_VC.outputs.analysis}}"

      - name: SDK - Build
        shell: cmd
        run: |
          @echo off
          msbuild "build/CLEO_SDK.sln" /property:Configuration=Release /property:Platform=Win32 /m /fileLogger1 /fileLoggerParameters1:warningsOnly;errorsOnly;logfile=output.log
          node .github/workflows/analyze-build-log.js "SDK compilation"

      - name: SDK - VirusTotal scan
        id: scan_plugins
        env:
          vt_key: ${{secrets.VT_KEY}}
        if: ${{env.vt_key != ''}}
        uses: crazy-max/ghaction-virustotal@d34968c958ae283fe976efed637081b9f9dcf74f # v4.2.0
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          files: './bin/CLEO/CLEO_PLUGINS/*.cleo'

      - name: SDK - VirusTotal log
        if: steps.scan_plugins.outcome == 'success'
        run: echo "::notice title=CLEO plugins virus scan::${{steps.scan_plugins.outputs.analysis}}"

      - name: Gather output files
        shell: cmd
        run: |
          @echo Create III base directories
          # mkdir .output\III\CLEO_Readme
          mkdir .output\III\CLEO\CLEO_PLUGINS

          @echo Create VC base directories
          # mkdir .output\VC\CLEO_Readme
          mkdir .output\VC\CLEO\CLEO_PLUGINS

          @echo Copy GTA III files
          # copy CHANGELOG.md             .output\III\CLEO_Readme\CHANGELOG.md
          # copy Readme_III.md            .output\III\CLEO_Readme\Readme.md
          copy bin\III.CLEO.asi         .output\III\III.CLEO.asi
          for %%f in (bin\CLEO\CLEO_PLUGINS\III.*.cleo) do copy %%f .output\III\CLEO\CLEO_PLUGINS\

          @echo Copy GTA VC files
          # copy CHANGELOG.md             .output\VC\CLEO_Readme\CHANGELOG.md
          # copy Readme_VC.md             .output\VC\CLEO_Readme\Readme.md
          copy bin\VC.CLEO.asi          .output\VC\VC.CLEO.asi
          for %%f in (bin\CLEO\CLEO_PLUGINS\VC.*.cleo) do copy %%f .output\VC\CLEO\CLEO_PLUGINS\

      - name: Pack archive - III.CLEO
        uses: ThirteenAG/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464 # master
        with:
          path: ./.output/III/*
          type: "zip"
          filename: III.CLEO-${{ github.ref_name }}.zip
          exclusions: "*.pdb *.lib *.exp"

      - name: Pack archive - VC.CLEO
        uses: ThirteenAG/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464 # master
        with:
          path: ./.output/VC/*
          type: "zip"
          filename: VC.CLEO-${{ github.ref_name }}.zip
          exclusions: "*.pdb *.lib *.exp"

      - name: Create release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.read_version.outputs.version }}
          bodyFile: 'changes.txt'
          tag: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
          artifacts: "III.CLEO*.zip,VC.CLEO*.zip"
          allowUpdates: true
